services:
  nginx:
    image: nginx:latest
    container_name: ecom_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecom_app
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: ecom_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ecom_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecom_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

  admin-app:
    build:
      context: ./admin-app
      dockerfile: Dockerfile
    container_name: ecom_admin_app
    volumes:
      - ./admin-app:/app
      - admin_node_modules:/app/node_modules
    networks:
      - app-network

  public-app:
    build:
      context: ./public-app
      dockerfile: Dockerfile
    container_name: ecom_public_app
    ports:
      - "5174:5173"
    volumes:
      - ./public-app:/app
      - public_node_modules:/app/node_modules
    networks:
      - app-network

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecom_worker
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      - db
      - app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    command: >
      php artisan queue:work
      --queue=images,default
      --sleep=3
      --tries=3
      --timeout=1200
      -vvv
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  admin_node_modules:
  public_node_modules: