; Увеличиваем максимальный размер POST-запроса (например, до 50 МБ)
post_max_size = 50M
; Увеличиваем максимальный размер загружаемых файлов
upload_max_filesize = 50M
; Увеличиваем лимит оперативной памяти для одного PHP-скрипта
memory_limit = 512M